import React from 'react';
import TextField from '@material-ui/core/TextField';
import Autocomplete from '@material-ui/lab/Autocomplete';

export default  function School() {
    return (
      <Autocomplete 
        id="School"
        options={school}
        style={{ width: '100%' , backgroundColor: 'white'}}
        getOptionLabel={(option) =>option}
        renderInput={(params) => <TextField {...params} label='School*' variant="outlined" />}
      />
    );
  }
  const school = [
            'Massachusetts Institute of Technology  us',
           	'Harvard University	 us',
        	'Stanford University  us',
            'Cornell University	 us',
            'University of California, Berkeley us',
            'Johns Hopkins University us',
            'Columbia University in the City of New York us',
            'University of Michigan us',
            'University of Washington us',
            'University of Minnesota-Twin Cities	 us',
            'Penn State University	 us',
            'University of California, Los Angeles	 us',
            'University of Pennsylvania	 us',
            'University of Toronto  ca',
            'Yale University	 us',
            'Purdue University us',
            'The University of Texas at Austin	us',
            'University of Oxford	United Kingdom gb',
            'New York University	 us',
            'University of Wisconsin-Madison	 us',
            'Carnegie Mellon University	 us',
            'University of Southern California us',
            'Princeton University	 us',
            'The University of British Columbia	 ca',
            'University of Chicago	 us',
            'University of Cambridge	  gb',
            'Arizona State University us',
            'University of Illinois at Urbana-Champaign	 us',
            'Michigan State University	 us',
            'University of California, San Diego	 us',
            'University of California, Irvine	 us',
            'University of Florida	 us',
            'University of California, Davis	 us',
            'Duke University	 us',
            'Northwestern University	 us',
            'University of North Carolina at Chapel Hill	 us',
            'University of Colorado Boulder	 us',
            'Rutgers, The State University of New Jersey	 us',
            'The University of Arizona	 us',
            'University of Maryland	 us',
            'Boston University	 us',
            'The University of Utah	 us',
            'Texas A&M University	 us',
            'University of Virginia	 us',
            'The Ohio State University	 us',
            'University College London	United Kingdom gb',
            'Simon Fraser University	 ca',
            'Georgia Institute of Technology	 us',
            'McGill University	 ca',
            'Xian Jiaotong University cn',
            'University of Pittsburgh us',
            'Eidgenössische Technische Hochschule Zürich	Switzerland ch',
            'Peking University cn',
            'North Carolina State University	 us',
            'The University of Edinburgh	United Kingdom gb',
            'University of Waterloo	 ca',
            'Indiana University Bloomington	 us',
            'Universidade de São Paulo	Brazil br',
            'Universidad Nacional Autónoma de México	Mexico mx',
            'Shanghai Jiao Tong University	China cn',
            'Virginia Polytechnic Institute and State University us',
            'Oregon State University	 us',
            'Washington University in St. Louis	 us',
            'University of California, Santa Barbara us',
            'Hunan University	China cn',
            'California Institute of Technology	 us',
            'Florida State University	 us',
            'University of Massachusetts Amherst us',
            'Brigham Young University us',
            'Tufts University	 us',
            'University of Nebraska-Lincoln	 us',
            'Georgetown University	 us',
            'University of Georgia	 us',
            'The University of Sydney	Australia au',
            'The University of Melbourne	Australia au',
            'Monash University	Australia au',
            'Universität Wien	Austria at',
            'Iowa State University	 us',
            'Jinan University  cn',
            'The University of Manchester gb',
            'University of Rochester us',
            'University of Iowa	 us',
            'University of South Florida us',
            'The University of New South Wales	Australia au',
            'George Washington University	 us',
            'York University	 ca',
            'Washington State University us',
            'Brown University	 us',
            'University of Houston	 us',
            'University at Buffalo, State University of New York us',
            'University of Alberta	 ca',
            'Dartmouth College	 us',
            'Vanderbilt University	 us',
            'Shenzhen University	China cn',
            'University of Delaware	 us',
            'National University of Singapore	Singapore sg',
            'Georgia State University	 us',
            'The London School of Economics and Political Science	United Kingdom gb',
            'The University of Tokyo	Japan jp',
            'Queen s University	 ca',
            'William Marsh Rice University	 us',
            'University of Illinois at Chicago	 us',
            'University of Glasgow	United Kingdom gb',
            'University of California, Riverside	 us',
            'University of California, Santa Cruz	 us',
            'Universidad Complutense de Madrid	Spain es',
            'Université de Strasbourg	France fr',
            'Universidad de Barcelona	Spain es',
            'Guangxi University	China cn',
            'Colorado State University	 us',
            'Helsingin yliopisto	Finland fi',
            'Australian National University	Australia au',
            'University of Notre Dame	 us',
            'University of Oregon	 us',
            'Ludwig-Maximilians-Universität München	Germany de',
            'Katholieke Universiteit Leuven	Belgium be',
            'University of Central Florida	 us',
            'Emory University	 us',
            'The University of Queensland	Australia au',
            'University of California, San Francisco us',
            'University of Calgary	 ca',
            'King Saud University	Saudi Arabia sa',
            'University of Connecticut	 us',
            'Imperial College London	United Kingdom gb',
            'Freie Universität Berlin	Germany de',
            'Moscow State University	Russia ru',
            'Universiteit Utrecht	Netherlands nl',
            'Universiteit van Amsterdam	Netherlands nl',
            'Tsinghua University	China cn',
            'University of New Mexico	 us',
            'Syracuse University	 us',
            'Université de Lorraine	France fr',
            'Northeastern University	 us',
            'McMaster University	 ca',
            'Nanyang Technological University	Singapore sg',
            'University of Kansas	 us',
            'Københavns Universitet	Denmark dk',
            'University of Victoria	 ca',
            'George Mason University	 us',
            'University of Missouri	 us',
            'University of Kentucky	 us',
            'Université de Montréal	 ca',
            'Universitetet i Oslo	Norway no',
            'The University of Hong Kong	Hong Kong hk',
            'The University of Warwick	United Kingdom gb',
            'Rheinisch-Westfälische Technische Hochschule Aachen	Germany de',
            'Western University	 ca',
            'National Research University Higher School of Economics	Russia ru',
            'Ryerson University	 ca',
            'Anadolu Üniversitesi	Turkey tr',
            'National Taiwan University	Taiwan tw',
            'Zhejiang University	 cn',
            'Temple University	 us',
            'Ruhr-Universität Bochum	Germany de',
            'University of Southampton	United Kingdom gb',
            'University of Leeds	United Kingdom gb',
            'Universidad de La Rioja	Spain es',
            'Université Laval	 ca',
            'The University of Tennessee, Knoxville	 us',
            'Florida International University us',
            'Kyoto University	Japan jp',
            'Technische Universität München	Germany de',
            'Tecnológico de Monterrey	Mexico mx',
            'Drexel University	 us',
            'San Diego State University	 us',
            'University of Science and Technology of China	 cn',
            'The University of Nottingham gb',
            'University of Liverpool  gb',
            'École Polytechnique Fédérale de Lausanne	Switzerland ch',
            'Rochester Institute of Technology	 us',
            'University of Birmingham	United Kingdom gb',
            'University of Miami	 us',
            'Newcastle University	United Kingdom gb',
            'Concordia University	 ca',
            'California State University, Northridge us',
            'The University of Alabama	 us',
            'Kungliga Tekniska högskolan	Sweden se',
            'Universiteit Leiden	Netherlands nl',
            'Universität Zürich	Switzerland ch',
            'University of Auckland	New Zealand nz',
            'Universidad de Chile	Chile cl',
            'Université de Liège	Belgium be',
            'Université Clermont Auvergne	 fr',
            'Kings College London	  gb',
            'Universidad de Valencia	Spain es',
            'Louisiana State University	 us',
            'The University of Oklahoma	 us',
            'University of Cincinnati	 us',
            'The Chinese University of Hong Kong hk',
            'University of South Carolina us',
            'Boston College	 us',
            'Heriot-Watt University	  gb',
            'Uppsala Universitet	Sweden se',
            'The University of York	United  gb',
            'Technische Universität Wien	Austria at',
            'Lunds Universitet	Sweden se',
            'Carleton University ca',
            'Ruprecht-Karls-Universität Heidelberg	Germany de',
            'Technische Universiteit Delft	Netherlands nl',
            'Sun Yat-Sen University	China cn'
  ];